### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by vovan-T** [omicron-b/unturbo-web#1]
App don't see "turbo" in this link.
https://yandex.ru/turbo?text=https%3A%2F%2Ffishki.net%2Fvideo%2F4537618-chinovnik-v-prjamom-jefire-vozmutilsja-prosybe-zhitelej-poch.html&utm_source=aab&platform=desktop

**Comment by omicron-b** [comment]
@Voland-1 
this is fixed now, thanks a lot for the report and sorry it took me so long

**Comment by omicron-b** [comment]
fixed the same issue for Firefox extension in
https://github.com/omicron-b/unturbo/commit/19ad2e400493b76e60b8fa06d6c5ba21e8b1aa2c
